---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: observability
data:
  config.yaml: |
    server:
      log_level: info
    traces:
      configs:
      - name: kubernetes-traces
        receivers:
          jaeger:
            protocols:
              thrift_http: # For Mimir (port 14268)
          opencensus: # For Linkerd (port 55678)
          otlp:
            protocols:
              grpc: # For Nginx Ingress (port 4317)
        remote_write:
        - endpoint: tempo-distributor.tempo.svc:55680
          insecure: true
          retry_on_failure:
            enabled: true
          headers:
            X-Scope-OrgID: _local
