---
config:
  clients:
  - url: http://loki-write.loki.svc:3100/loki/api/v1/push
    tenant_id: _local

tolerations:
- effect: NoSchedule
  operator: Exists

serviceMonitor:
  enabled: true
  labels:
    release: monitor