---
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: http://mimir-distributor-lgtm-central.mimir.svc:8080/api/v1/push
      headers:
        X-Scope-OrgID: remote02
      queueConfig:
        capacity: 5000
        minShards: 1
        maxShards: 50
        maxSamplesPerSend: 1000
      writeRelabelConfigs:
      - sourceLabels: [namespace]
        regex: "^linkerd.*"
        action: drop

grafana:
  enabled: false
