# Warning: there won't be any resource requests/limits for any Mimir-related container
---
fullnameOverride: mimir

serviceAccount: # There is no way to set an account per component
  create: true
  name: mimir-sa

global:
  clusterDomain: lgtm-central.cluster.local

  extraEnv:
  - name: JAEGER_ENDPOINT
    value: 'http://grafana-agent.observability.svc:14268/api/traces'
  - name: JAEGER_SAMPLER_TYPE
    value: 'const'
  - name: JAEGER_SAMPLER_PARAM
    value: '1'

rbac:
  create: false

mimir:
  structuredConfig:
    multitenancy_enabled: true
    usage_stats:
      enabled: false
    server:
      grpc_server_max_concurrent_streams: 1000
    common:
      storage:
        backend: s3
        s3: # Based on values-minio.yaml
          endpoint: minio.storage.svc:9000
          access_key_id: remote_user
          secret_access_key: R3m0t3us3r
          insecure: true
    distributor:
      instance_limits:
        max_ingestion_rate: 30000 # Per-distributor rate limit
        max_inflight_push_requests: 250
    ingester:
      ring:
        num_tokens: 512
        unregister_on_shutdown: false
    frontend:
      log_queries_longer_than: 1m
    limits:
      ingestion_rate: 30000 # Per-user rate limit
      max_global_series_per_user: 1000000 # To accomodate one big tenant
      max_global_series_per_metric: 100000
      max_label_names_per_series: 100
      # Allow ingestion of out-of-order samples up to 15 minutes since the latest received sample for the series.
      # https://grafana.com/docs/mimir/latest/operators-guide/configure/configure-out-of-order-samples-ingestion/
      out_of_order_time_window: 15m
      max_cache_freshness: 15m
    blocks_storage:
      s3:
        bucket_name: mimir-data
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
    alertmanager_storage:
      s3:
        bucket_name: mimir-ruler

runtimeConfig:
  ingester_limits:
    max_inflight_push_requests: 250
    max_ingestion_rate: 30000
    max_series: 1000000

nginx:
  enabled: false

minio:
  enabled: false

overrides_exporter:
  resources: null

ruler:
  resources: null
  affinity: null
  initContainers:
  - name: wait
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'until nslookup mimir-chunks-cache; do echo waiting for memcached; sleep 2; done']

alertmanager:
  resources: null
  affinity: null

distributor:
  replicas: 2
  resources: null
  affinity: null

ingester:
  replicas: 3
  persistentVolume:
    size: 20Gi
  resources: null
  affinity: null

compactor:
  replicas: 2
  persistentVolume:
    size: 10Gi
  resources: null
  affinity: null

querier:
  replicas: 3
  resources: null
  affinity: null
  initContainers:
  - name: wait
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'until nslookup mimir-metadata-cache; do echo waiting for memcached; sleep 2; done']

query_frontend:
  replicas: 2
  resources: null
  affinity: null
  initContainers:
  - name: wait
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'until nslookup mimir-results-cache; do echo waiting for memcached; sleep 2; done']

query_scheduler:
  enabled: false

store_gateway:
  replicas: 3
  persistentVolume:
    size: 10Gi
  resources: null
  affinity: null
  initContainers:
  - name: wait
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'until nslookup mimir-metadata-cache; do echo waiting for memcached; sleep 2; done']

chunks-cache:
  enabled: true
  replicas: 3
  allocatedMemory: 1024
  resources:
    requests:
      cpu: 25m
  affinity: null

index-cache:
  enabled: true
  replicas: 3
  allocatedMemory: 768
  resources:
    requests:
      cpu: 25m
  affinity: null

metadata-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 384
  resources:
    requests:
      cpu: 25m
  affinity: null

results-cache:
  enabled: true
  replicas: 2
  allocatedMemory: 512
  resources:
    requests:
      cpu: 25m
  affinity: null

metaMonitoring:
  serviceMonitor:
    enabled: true
    clusterLabel: null
    labels:
      release: monitor
