---
serviceAccount:
  create: true
  name: promtail-sa

tolerations:
- effect: NoSchedule
  operator: Exists

serviceMonitor:
  enabled: false # There are template issues
  labels:
    release: monitor