---
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: http://mimir-distributor-lgtm-central.mimir.svc:8080/api/v1/push
      headers:
        X-Scope-OrgID: remote01

prometheusOperator:
  clusterDomain: lgtm-remote.cluster.local

grafana:
  enabled: false